name: Android Espresso Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  espresso-test:
    name: Run Espresso Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execution permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run instrumented tests (Espresso)
        run: ./gradlew connectedDebugAndroidTest
